### ISSUE TITLE
Unable to register a geometry (500 code each time)

### ISSUE THREAD

**Issue by SwampGuzzler** [gfw-api/gfw-geostore-api#8]
I am having a hard time registering user-generated GeoJSON. I have sent in a variety of features, polygons, and FeatureCollections to this API but have been unable to get a 200 response back. I have taken several of these from the repo's unit tests and run many requests out of the GEOSTORE docs so I am not sure what I am doing wrong. 

From the docs:
![screen shot 2016-11-29 at 8 50 16 am](https://cloud.githubusercontent.com/assets/5713523/20712244/4b923696-b611-11e6-9c40-4d508d547c0b.png)

Custom GeoJSON:
![screen shot 2016-11-29 at 8 52 30 am](https://cloud.githubusercontent.com/assets/5713523/20712292/70bafe08-b611-11e6-933c-65dd32586c6a.png)

I would like to run Biomass Loss calls against the gfw-api, but first I need to register the user's geometry, so any help would be appreciated!

**Comment by rrequero** [comment]
Hello, 

the problem is the content-type, is necessary that you set content-type to application/json

Thanks

**Comment by SwampGuzzler** [comment]
Thanks Raul!
